import Product1 from "../../../../assets/images/products/product-img-1.jpg";
import Product2 from "../../../../assets/images/products/product-img-2.jpg";
import Product3 from "../../../../assets/images/products/product-img-3.jpg";
import Product4 from "../../../../assets/images/products/product-img-4.jpg";
import Product5 from "../../../../assets/images/products/product-img-5.jpg";
import Product6 from "../../../../assets/images/products/product-img-6.jpg";
import Product7 from "../../../../assets/images/products/product-img-7.jpg";
import Product8 from "../../../../assets/images/products/product-img-8.jpg";
import Product9 from "../../../../assets/images/products/product-img-9.jpg";
import Product10 from "../../../../assets/images/products/product-img-10.jpg";
import Product11 from "../../../../assets/images/products/product-img-11.jpg";
import Product12 from "../../../../assets/images/products/product-img-12.jpg";

import Product13 from "../../../../assets/images/products/product-img-13.jpg";
import Product14 from "../../../../assets/images/products/product-img-14.jpg";
import Product20 from "../../../../assets/images/products/product-img-20.jpg";
import Product21 from "../../../../assets/images/products/product-img-21.jpg";
import Product22 from "../../../../assets/images/products/product-img-22.jpg";
import Product23 from "../../../../assets/images/products/product-img-23.jpg";
import Product24 from "../../../../assets/images/products/product-img-24.jpg";
import Product26 from "../../../../assets/images/products/product-img-26.jpg";
import Product27 from "../../../../assets/images/products/product-img-27.jpg";

export const productsData = [
  {
    id: 14,
    productImg: Product1,
    images: [
      { productImg: Product1 },
      { productImg: Product1 },
      { productImg: Product1 },
      { productImg: Product1 },
    ],
    sale: "Sale",
    category: "Snack & Munchies",
    productName: "Haldiram's Sev Bhujia",
    rating: "4.5",
    sold: "149",
    currentPrice: "18",
    previousPrice: "24",
    off: 6,
    reviews: "45",
    productCode: "FBB00106",
    availability: "In Stock",
    type: "Snack",
    weight: "1 kg",
    action: "Add to Cart",

  },
  {
    id: 15,
    productImg: Product2,
    images: [
      { productImg: Product2 },
      { productImg: Product2 },
      { productImg: Product2 },
      { productImg: Product2 },
    ],
    category: "Bakery & Biscuits",
    productName: "NutriChoice Digestive Biscuits",
    rating: "4.5",
    sold: "25",
    currentPrice: "24",
    reviews: "40",
    productCode: "FBB00107",
    availability: "In Stock",
    type: "Biscuits",
    weight: "250 g",
    action: "Add to Cart",

  },
  {
    id: 16,
    productImg: Product3,
    images: [
      { productImg: Product3 },
      { productImg: Product3 },
      { productImg: Product3 },
      { productImg: Product3 },
    ],
    category: "Bakery & Biscuits",
    productName: "Cadbury 5 star chocolate",
    rating: "5",
    sold: "469",
    currentPrice: "32",
    previousPrice: "35",
    off:3,
    reviews: "70",
    productCode: "FBB00108",
    availability: "In Stock",
    type: "Chocolate",
    weight: "1 kg",
    action: "Add to Cart",
  },
  {
    id: 17,
    productImg: Product4,
    images: [
      { productImg: Product4 },
      { productImg: Product4 },
      { productImg: Product4 },
      { productImg: Product4 },
    ],
    sale: "Hot",
    category: "Snack & Munchies",
    productName: "Onion Flavour Potato",
    rating: "3.5",
    sold: "456",
    currentPrice: "3",
    previousPrice: "5",
    off: 2,
    reviews: "100",
    productCode: "FBB00109",
    availability: "In Stock",
    type: "Snack",
    weight: "250 kg",
    action: "Add to Cart",
  },
  {
    id: 18,
    productImg: Product11,
    images: [
      { productImg: Product11 },
      { productImg: Product11 },
      { productImg: Product11 },
      { productImg: Product11 },
    ],
    category: "Tea, Coffee & Drinks",
    productName: "Nestle Coffee",
    rating: "4.5",
    sold: "350",
    currentPrice: "12",
    previousPrice: "18",
    weight: "1 kg",
    action: "Add to Cart",
  },
  {
    id: 19,
    productImg: Product5,
    images: [
      { productImg: Product5 },
      { productImg: Product5 },
      { productImg: Product5 },
      { productImg: Product5 },
    ],
    category: "Instant Food",
    productName: "Salted Instant Popcorn",
    rating: "4.5",
    sold: "39",
    currentPrice: "13",
    previousPrice: "18",
    off: 5,
    reviews: "32",
    productCode: "FBB00110",
    availability: "Out of Stock",
    type: "Popcorn",
    weight: "1 kg",
    action: "Add to Cart",
  },
  {
    id: 20,
    productImg: Product6,
    images: [
      { productImg: Product6 },
      { productImg: Product6 },
      { productImg: Product6 },
      { productImg: Product6 },
    ],
    sale: "Sale",
    category: "Dairy, Bread & Eggs",
    productName: "Blueberry Greek Yogurt",
    rating: "4.5",
    sold: "189",
    currentPrice: "18",
    previousPrice: "24",
    off: 6,
    reviews: "45",
    productCode: "FBB00111",
    availability: "In Stock",
    type: "Yogurt",
    weight: "1 kg",
    action: "Add to Cart",
  },
  {
    id: 21,
    productImg: Product7,
    images: [
      { productImg: Product7 },
      { productImg: Product7 },
      { productImg: Product7 },
      { productImg: Product7 },
    ],
    category: "Dairy, Bread & Eggs",
    productName: "Britannia Cheese Slices",
    rating: "5",
    sold: "345",
    currentPrice: "24",
    reviews: "58",
    productCode: "FBB00121",
    availability: "In Stock",
    type: "Cheese",
    weight: "1 kg",
    action: "Add to Cart",
  },
  {
    id: 22,
    productImg: Product8,
    images: [
      { productImg: Product8 },
      { productImg: Product8 },
      { productImg: Product8 },
      { productImg: Product8 },
    ],
    category: "Instant Food",
    productName: "Kellogg's Original Cereal",
    rating: "4",
    sold: "90",
    currentPrice: "32",
    previousPrice: "35",
    off: 3,
    reviews: "45",
    productCode: "FBB00112",
    availability: "In Stock",
    type: "Cereals",
    weight: "1 kg",
    action: "Add to Cart",
  },
  {
    id: 23,
    productImg: Product9,
    images: [
      { productImg: Product9 },
      { productImg: Product9 },
      { productImg: Product9 },
      { productImg: Product9 },
    ],
    category: "Snack & Munchies",
    productName: "Slurrp Millet Chocolate",
    rating: "4.5",
    sold: "67",
    currentPrice: "3",
    previousPrice: "5",
    off: 2,
    reviews: "65",
    productCode: "FBB00122",
    availability: "In Stock",
    type: "Chocolate",
    weight: "1 kg",
    action: "Add to Cart",
  },
  {
    id: 24,
    productImg: Product10,
    images: [
      { productImg: Product10 },
      { productImg: Product10 },
      { productImg: Product10 },
      { productImg: Product10 },
    ],
    category: "Dairy, Bread & Eggs",
    productName: "Amul Butter - 500 g",
    rating: "3.5",
    sold: "89",
    currentPrice: "13",
    previousPrice: "18",
    off: 5,
    reviews: "49",
    productCode: "FBB00123",
    availability: "In Stock",
    type: "Butter",
    weight: "1 kg",
    action: "Add to Cart",
  },
  {
    id: 25,
    productImg: Product5,
    images: [
      { productImg: Product5 },
      { productImg: Product5 },
      { productImg: Product5 },
      { productImg: Product5 },
    ],
    category: "Instant Food",
    productName: "Sweet Instant Popcorn",
    rating: "4.5",
    sold: "26",
    currentPrice: "13",
    previousPrice: "18",
    off: 5,
    reviews: "95",
    productCode: "FBB00124",
    availability: "In Stock",
    type: "Popcorn",
    weight: "1 kg",
    action: "Add to Cart",
  },
  {
    id: 26,
    productImg: Product11,
    images: [
      { productImg: Product11 },
      { productImg: Product11 },
      { productImg: Product11 },
      { productImg: Product11 },
    ],
    category: "Tea, Coffee & Drinks",
    productName: "Roasted Ground Coffee",
    rating: "4.5",
    sold: "410",
    currentPrice: "12",
    previousPrice: "18",
    off: 6,
    reviews: "42",
    productCode: "FBB00125",
    availability: "out of Stock",
    type: "Coffee",
    weight: "1 kg",
    action: "Add to Cart",
  },
  {
    id: 27,
    productImg: Product12,
    images: [
      { productImg: Product12 },
      { productImg: Product12 },
      { productImg: Product12 },
      { productImg: Product12 },
    ],
    category: "Fruits & Vegetables",
    productName: "Crushed Tomatoes",
    rating: "4.5",
    sold: "230",
    currentPrice: "62",
    previousPrice: "70",
    off: 8,
    reviews: "73",
    productCode: "FBB00126",
    availability: "In Stock",
    type: "Vegetable",
    weight: "1 kg",
    action: "Add to Cart",
  },
  {
    id: 28,
    productImg: Product8,
    images: [
      { productImg: Product8 },
      { productImg: Product8 },
      { productImg: Product8 },
      { productImg: Product8 },
    ],
    category: "Instant Food",
    productName: "Corn Flask",
    rating: "4",
    sold: "80",
    currentPrice: "32",
    previousPrice: "35",
    off: 3,
    reviews: "25",
    productCode: "FBB00127",
    availability: "In Stock",
    type: "Cereals",
    weight: "1 kg",
    action: "Add to Cart",
  },
  {
    id:29,
    productImg: Product10,
    images: [
      { productImg: Product10 },
      { productImg: Product10 },
      { productImg: Product10 },
      { productImg: Product10 },
    ],
    category: "Dairy, Bread & Eggs",
    productName: "Amul Butter - 250 g",
    rating: "3.5",
    sold: "210",
    currentPrice: "7",
    previousPrice: "12",
    off: 5,
    reviews: "85",
    productCode: "FBB00128",
    availability: "In Stock",
    type: "Butter",
    weight: "250 g",
    action: "Add to Cart",
  },
  {
    id:30,
    productImg: Product4,
    images: [
      { productImg: Product4 },
      { productImg: Product4 },
      { productImg: Product4 },
      { productImg: Product4 },
    ],
    sale: "Hot",
    category: "Snack & Munchies",
    productName: "Lays Potato Chips",
    rating: "3.5",
    sold: "545",
    currentPrice: "3",
    previousPrice: "5",
    off: 2,
    reviews: "45",
    productCode: "FBB00129",
    availability: "Out of Stock",
    type: "Snacks",
    weight: "250 g",
    action: "Add to Cart",
  },
  {
    id:31,
    productImg: Product1,
    images: [
      { productImg: Product1 },
      { productImg: Product1 },
      { productImg: Product1 },
      { productImg: Product1 },
    ],
    sale: "Sale",
    category: "Snack & Munchies",
    productName: "Haldiram's Mix Nimko",
    rating: "4.5",
    sold: "240",
    currentPrice: "18",
    previousPrice: "24",
    off: 6,
    reviews: "44",
    productCode: "FBB00130",
    availability: "Out of Stock",
    type: "Munchies",
    weight: "1 kg",
    action: "Add to Cart",
  },
  {
    id:32,
    productImg: Product2,
    images: [
      { productImg: Product2 },
      { productImg: Product2 },
      { productImg: Product2 },
      { productImg: Product2 },
    ],
    category: "Bakery & Biscuits",
    productName: "Wheat Biscuits",
    rating: "4",
    sold: "480",
    currentPrice: "15",
    previousPrice: "21",
    off: 6,
    reviews: "46",
    productCode: "FBB00131",
    availability: "Out of Stock",
    type: "Biscuits",
    weight: "1 kg",
    action: "Add to Cart",
  },
  {
    id:33,
    productImg: Product12,
    images: [
      { productImg: Product12 },
      { productImg: Product12 },
      { productImg: Product12 },
      { productImg: Product12 },
    ],
    category: "Fruits & Vegetables",
    productName: "Tomatoe Purry",
    rating: "4.5",
    sold: "200",
    currentPrice: "73",
    previousPrice: "80",
    off: 7,
    reviews: "25",
    productCode: "FBB00132",
    availability: "In Stock",
    type: "Vegetables",
    weight: "1 kg",
    action: "Add to Cart",
    
  },

  // {
  //   image: Product13,
  //   productCategory: "Baby Care",
  //   productName: "Baby Essentials",
  //   rating: "4",
  //   sold: "430",
  //   currentPrice: "83",
  //   previousPrice: "90",
  // },
  // {
  //   image: Product14,
  //   productCategory: "Bakery & Biscuits",
  //   productName: "Oats & Wheat Biscuits",
  //   rating: "4",
  //   sold: "560",
  //   currentPrice: "15",
  //   previousPrice: "21",
  // },
  // {
  //   image: Product20,
  //   sale: "Sale",
  //   productCategory: "Instant Food",
  //   productName: "Corn Flasks",
  //   rating: "4.5",
  //   sold: "200",
  //   currentPrice: "24",
  //   previousPrice: "30",
  // },
  // {
  //   image: Product21,
  //   productCategory: "Tea, Coffee a7 Drink",
  //   productName: "Nestle Choco Powder & BournVita",
  //   rating: "4.5",
  //   sold: "300",
  //   currentPrice: "30",
  //   previousPrice: "36",
  // },
  // {
  //   image: Product22,
  //   sale: "Hot",
  //   productCategory: "Snack & Munchies",
  //   productName: "Lays Classic Chips",
  //   rating: "4",
  //   sold: "500",
  //   currentPrice: "8",
  //   previousPrice: "10",
  // },
  // {
  //   image: Product23,
  //   productCategory: "Chicken, meat & Fish",
  //   productName: "Chicken - 1 kg",
  //   rating: "4.5",
  //   sold: "250",
  //   currentPrice: "36",
  // },

  // {
  //   image: Product24,
  //   sale: "Hot",
  //   productCategory: "Cleaning Essentials",
  //   productName: "Surf Excel + Harpik",
  //   rating: "4.5",
  //   sold: "150",
  //   currentPrice: "20",
  //   previousPrice: "25",
  // },
  // {
  //   image: Product26,
  //   productCategory: "Atta, Rice & Dal",
  //   productName: "Atta - 10kg",
  //   rating: "4",
  //   sold: "400",
  //   currentPrice: "200",

  // },
  // {
  //   image: Product27,
  //   productCategory: "Dairy, Bread & Eggs",
  //   productName: "Bread",
  //   rating: "4.5",
  //   sold: "450",
  //   currentPrice: "10",
  //   previousPrice: "12",
  // },
  // {
  //   image: Product23,
  //   productCategory: "Frozen Foods",
  //   productName: "Chicken Slices",
  //   rating: "4",
  //   sold: "180",
  //   currentPrice: "15",
  //   previousPrice: "18",
  // },
];
